#!/usr/bin/env node
var argv = require('optimist').argv
  , path = require('path')
  , exec = require('child_process').exec
  , node
  , config
  , args = process.argv.splice(2)
  , fs = require('fs')
  , tests = [ 'test.persistence.js'
            ]
  ;

var run = function(adaptor, test, cb) {
  cb = cb || function(){};
  if (adaptor) {
    console.log('------------------------------------');
    console.log('Run Test: ' + adaptor + ' - ' + test);
    console.log('------------------------------------');
  }
  switch (adaptor) {
    case 'mysql':
      config = {
        adaptor: 'mysql',
        database: 'nodejs_mysql',
        host: 'localhost',
        port: 3306,
        user: 'root',
        password: ''
      };
      break;
    case 'sqlite':
      config = {
        adaptor: 'sqlite',
        database: __dirname + '/test.db'
      };
      break;
    case 'memory':
      config = {
        adaptor: 'memory',
        database: 'test'
      };
      break;
    default:
      run('memory', test, function(){
        run('mysql', test, function() {
          run('sqlite', test, function() {
          });
        });
      });
      // console.error('NOTICE: Specify database adaptor');
      // console.error('$ ./run-tests [mysql|sqlite|memory]');
      return;
  };
  
  fs.writeFileSync('config.json', JSON.stringify(config));
  node = exec('node ' + test, cb);

  node.stdout.on('data', function(data) {
    console.log(data.replace(/[\s\r\n]+$/, ''));
  });

  node.stderr.on('data', function(data) {
    console.error(data.replace(/[\s\r\n]+$/, ''));
  });

  process.on('SIGINT', function() {
    node.kill();
  });
};

var test = __dirname + '/' +args.pop();
path.exists(test, function(exists) {
  if (exists) tests = [test];
  tests.forEach(function(test) {
    run(argv.a, test);
  });
});
